### ISSUE TITLE
mobile nav menu overlay

### ISSUE THREAD

**Issue by rhema-ray** [Finney06/ProDevs#7]
```html
<div class="overlay has-fade"></div>
```
I don't believe this `div`  (lines 17-18) responsible for the overlay should be in the header tag but under it, somewhere around the top of the main element. Placing it in the header tag will only result in an unexpected bug.

**Comment by Finney06** [comment]
It works just fine, the main priority now should be on finishing up with the project before the deadline. We'll deliberate on better ways we could have written the code about later after the submission.
